# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/mhlee/LIBS/kinect calibration toolbox v2.1/capture"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/mhlee/LIBS/kinect calibration toolbox v2.1/capture"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/mhlee/LIBS/kinect calibration toolbox v2.1/capture/CMakeFiles" "/home/mhlee/LIBS/kinect calibration toolbox v2.1/capture/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/mhlee/LIBS/kinect calibration toolbox v2.1/capture/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kinect_capture

# Build rule for target.
kinect_capture: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kinect_capture
.PHONY : kinect_capture

# fast build rule for target.
kinect_capture/fast:
	$(MAKE) -f CMakeFiles/kinect_capture.dir/build.make CMakeFiles/kinect_capture.dir/build
.PHONY : kinect_capture/fast

freenect_module.o: freenect_module.cpp.o
.PHONY : freenect_module.o

# target to build an object file
freenect_module.cpp.o:
	$(MAKE) -f CMakeFiles/kinect_capture.dir/build.make CMakeFiles/kinect_capture.dir/freenect_module.cpp.o
.PHONY : freenect_module.cpp.o

freenect_module.i: freenect_module.cpp.i
.PHONY : freenect_module.i

# target to preprocess a source file
freenect_module.cpp.i:
	$(MAKE) -f CMakeFiles/kinect_capture.dir/build.make CMakeFiles/kinect_capture.dir/freenect_module.cpp.i
.PHONY : freenect_module.cpp.i

freenect_module.s: freenect_module.cpp.s
.PHONY : freenect_module.s

# target to generate assembly for a file
freenect_module.cpp.s:
	$(MAKE) -f CMakeFiles/kinect_capture.dir/build.make CMakeFiles/kinect_capture.dir/freenect_module.cpp.s
.PHONY : freenect_module.cpp.s

kinect_calibration.o: kinect_calibration.cpp.o
.PHONY : kinect_calibration.o

# target to build an object file
kinect_calibration.cpp.o:
	$(MAKE) -f CMakeFiles/kinect_capture.dir/build.make CMakeFiles/kinect_capture.dir/kinect_calibration.cpp.o
.PHONY : kinect_calibration.cpp.o

kinect_calibration.i: kinect_calibration.cpp.i
.PHONY : kinect_calibration.i

# target to preprocess a source file
kinect_calibration.cpp.i:
	$(MAKE) -f CMakeFiles/kinect_capture.dir/build.make CMakeFiles/kinect_capture.dir/kinect_calibration.cpp.i
.PHONY : kinect_calibration.cpp.i

kinect_calibration.s: kinect_calibration.cpp.s
.PHONY : kinect_calibration.s

# target to generate assembly for a file
kinect_calibration.cpp.s:
	$(MAKE) -f CMakeFiles/kinect_capture.dir/build.make CMakeFiles/kinect_capture.dir/kinect_calibration.cpp.s
.PHONY : kinect_calibration.cpp.s

kinect_capture.o: kinect_capture.cpp.o
.PHONY : kinect_capture.o

# target to build an object file
kinect_capture.cpp.o:
	$(MAKE) -f CMakeFiles/kinect_capture.dir/build.make CMakeFiles/kinect_capture.dir/kinect_capture.cpp.o
.PHONY : kinect_capture.cpp.o

kinect_capture.i: kinect_capture.cpp.i
.PHONY : kinect_capture.i

# target to preprocess a source file
kinect_capture.cpp.i:
	$(MAKE) -f CMakeFiles/kinect_capture.dir/build.make CMakeFiles/kinect_capture.dir/kinect_capture.cpp.i
.PHONY : kinect_capture.cpp.i

kinect_capture.s: kinect_capture.cpp.s
.PHONY : kinect_capture.s

# target to generate assembly for a file
kinect_capture.cpp.s:
	$(MAKE) -f CMakeFiles/kinect_capture.dir/build.make CMakeFiles/kinect_capture.dir/kinect_capture.cpp.s
.PHONY : kinect_capture.cpp.s

kinect_capture_app.o: kinect_capture_app.cpp.o
.PHONY : kinect_capture_app.o

# target to build an object file
kinect_capture_app.cpp.o:
	$(MAKE) -f CMakeFiles/kinect_capture.dir/build.make CMakeFiles/kinect_capture.dir/kinect_capture_app.cpp.o
.PHONY : kinect_capture_app.cpp.o

kinect_capture_app.i: kinect_capture_app.cpp.i
.PHONY : kinect_capture_app.i

# target to preprocess a source file
kinect_capture_app.cpp.i:
	$(MAKE) -f CMakeFiles/kinect_capture.dir/build.make CMakeFiles/kinect_capture.dir/kinect_capture_app.cpp.i
.PHONY : kinect_capture_app.cpp.i

kinect_capture_app.s: kinect_capture_app.cpp.s
.PHONY : kinect_capture_app.s

# target to generate assembly for a file
kinect_capture_app.cpp.s:
	$(MAKE) -f CMakeFiles/kinect_capture.dir/build.make CMakeFiles/kinect_capture.dir/kinect_capture_app.cpp.s
.PHONY : kinect_capture_app.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... kinect_capture"
	@echo "... rebuild_cache"
	@echo "... freenect_module.o"
	@echo "... freenect_module.i"
	@echo "... freenect_module.s"
	@echo "... kinect_calibration.o"
	@echo "... kinect_calibration.i"
	@echo "... kinect_calibration.s"
	@echo "... kinect_capture.o"
	@echo "... kinect_capture.i"
	@echo "... kinect_capture.s"
	@echo "... kinect_capture_app.o"
	@echo "... kinect_capture_app.i"
	@echo "... kinect_capture_app.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

